import { useState, useEffect, useCallback } from 'react'
import { supabase, isSupabaseConfigured } from '../lib/supabase'
import { useAuth } from './useAuth'

/**
 * Supabase-backed workspace hook.
 *
 * Single-workspace-per-user model for now: `profiles.default_workspace_id`
 * points to the workspace the user currently operates in. On signup a
 * default workspace is auto-created (handle_new_user trigger).
 *
 * Inviting a member:
 *   1. Insert a row in workspace_invites (token auto-generated)
 *   2. Call supabase.auth.signInWithOtp to send a magic-link email with the
 *      invite URL as redirect target
 *   3. Recipient clicks the link in email, lands authenticated on
 *      /invite/:token, client calls accept_workspace_invite RPC
 */
export function useWorkspace() {
  const { user, profile } = useAuth()
  const [workspace, setWorkspace] = useState(null)
  const [members, setMembers] = useState([])
  const [pendingInvites, setPendingInvites] = useState([])
  const [loading, setLoading] = useState(true)
  const [currentRole, setCurrentRole] = useState(null)

  const workspaceId = profile?.default_workspace_id || workspace?.id || null

  const refresh = useCallback(async () => {
    if (!isSupabaseConfigured() || !user || !workspaceId) {
      setWorkspace(null); setMembers([]); setPendingInvites([]); setLoading(false); return
    }
    setLoading(true)
    try {
      const [wsRes, memRes, invRes] = await Promise.all([
        supabase.from('workspaces').select('*').eq('id', workspaceId).single(),
        supabase.from('workspace_members').select('id, user_id, role, joined_at').eq('workspace_id', workspaceId),
        supabase.from('workspace_invites').select('*').eq('workspace_id', workspaceId).is('accepted_at', null),
      ])
      setWorkspace(wsRes.data || null)

      // Hydrate member emails/names from profiles in one round-trip
      const userIds = (memRes.data || []).map(m => m.user_id)
      let profilesById = {}
      if (userIds.length) {
        const { data: profs } = await supabase
          .from('profiles').select('id, full_name, email').in('id', userIds)
        profilesById = Object.fromEntries((profs || []).map(p => [p.id, p]))
      }
      const hydratedMembers = (memRes.data || []).map(m => ({
        id: m.id,
        userId: m.user_id,
        role: m.role,
        joinedAt: m.joined_at,
        email: profilesById[m.user_id]?.email || '',
        name: profilesById[m.user_id]?.full_name || '',
      }))
      setMembers(hydratedMembers)
      setPendingInvites(invRes.data || [])

      const me = hydratedMembers.find(m => m.userId === user.id)
      setCurrentRole(me?.role || null)
    } catch (e) {
      console.error('[useWorkspace] refresh failed', e)
    } finally {
      setLoading(false)
    }
  }, [user, workspaceId])

  useEffect(() => { refresh() }, [refresh])

  // Invite a new member — creates invite row + sends magic-link email.
  async function inviteMember(email, name = '', role = 'member') {
    if (!workspaceId || !user) return { error: 'no_workspace' }
    const cleanEmail = email.trim().toLowerCase()
    if (!cleanEmail) return { error: 'empty_email' }

    // Guard against inviting existing member
    const memberProfiles = members.map(m => m.email.toLowerCase())
    if (memberProfiles.includes(cleanEmail)) return { error: 'already_member' }
    if (pendingInvites.some(i => i.email.toLowerCase() === cleanEmail)) return { error: 'already_invited' }

    // Create invite row (token is auto-generated by DB default)
    const { data: invite, error: invErr } = await supabase
      .from('workspace_invites')
      .insert({ workspace_id: workspaceId, email: cleanEmail, name, role, invited_by: user.id })
      .select()
      .single()
    if (invErr) { console.error(invErr); return { error: invErr.message } }

    // Send magic-link email that redirects to /invite/:token
    const origin = typeof window !== 'undefined' ? window.location.origin : ''
    const { error: otpErr } = await supabase.auth.signInWithOtp({
      email: cleanEmail,
      options: {
        emailRedirectTo: `${origin}/invite/${invite.token}`,
        shouldCreateUser: true,
        data: { invited_to_workspace: workspaceId, invited_name: name },
      },
    })
    if (otpErr) {
      // Roll back invite row so we don't leak an orphan
      await supabase.from('workspace_invites').delete().eq('id', invite.id)
      return { error: otpErr.message }
    }

    await refresh()
    return { invite }
  }

  async function cancelInvite(inviteId) {
    const { error } = await supabase.from('workspace_invites').delete().eq('id', inviteId)
    if (error) return { error: error.message }
    await refresh()
    return { success: true }
  }

  async function removeMember(memberRowId) {
    const { error } = await supabase.from('workspace_members').delete().eq('id', memberRowId)
    if (error) return { error: error.message }
    await refresh()
    return { success: true }
  }

  async function updateMemberRole(memberRowId, newRole) {
    const { error } = await supabase.from('workspace_members').update({ role: newRole }).eq('id', memberRowId)
    if (error) return { error: error.message }
    await refresh()
    return { success: true }
  }

  async function updateWorkspaceName(name) {
    if (!workspaceId) return { error: 'no_workspace' }
    const { error } = await supabase.from('workspaces').update({ name }).eq('id', workspaceId)
    if (error) return { error: error.message }
    await refresh()
    return { success: true }
  }

  // Aggregate shape that mirrors the old localStorage hook as much as possible
  // so call-sites don't need to change much.
  const legacyShape = workspace
    ? {
        id: workspace.id,
        name: workspace.name,
        createdAt: workspace.created_at,
        members: members.map(m => ({
          id: m.id,
          email: m.email,
          name: m.name,
          role: m.role,
          joinedAt: m.joinedAt,
          status: 'active',
        })),
        pendingInvites: pendingInvites.map(i => ({
          id: i.id,
          email: i.email,
          name: i.name,
          role: i.role,
          invitedAt: i.invited_at,
          status: 'pending',
          token: i.token,
        })),
      }
    : null

  return {
    workspace: legacyShape,
    workspaceId,
    role: currentRole,
    loading,
    refresh,
    // Back-compat aliases
    createWorkspace: () => Promise.resolve({ error: 'auto_created' }), // no-op: trigger handles this
    inviteMember,
    cancelInvite,
    acceptInvite: () => Promise.resolve({ error: 'use_invite_page' }), // kept for API compat
    removeMember,
    updateMemberRole,
    updateWorkspaceName,
    memberCount: members.length,
    pendingCount: pendingInvites.length,
  }
}
